FROM python:3.11-slim

RUN apt-get update && apt-get install -y portaudio19-dev gcc

# Set work directory, copy requirements, etc.
WORKDIR /Backend
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . .
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]